### ISSUE TITLE
BadRequestException: 400 Bucket is requester pays bucket but no user project provided.

### ISSUE THREAD

**Issue by dneprDroid** [clintonreece/keras-cloud-ml-engine#3]
Sorry for disturbing. I have trial account on Google Cloud and got this error when a job was started:
```~$ export BUCKET_NAME=.........
~$ export JOB_NAME="mnist_mlp_train5_$(date +%Y%m%d_%H%M%S)"
~$ export JOB_DIR=gs://$BUCKET_NAME/$JOB_NAME
~$ export REGION=us-east1
~$ gcloud ml-engine jobs submit training $JOB_NAME     --job-dir $JOB_DIR     --runtime-version 1.0     --module-name trainer.mnist_m
lp     --package-path ./trainer     --region $REGION     --     --train-file gs://$BUCKET_NAME/data/mnist.pkl
```
Bucket storage:
```
~$ gsutil ls gs://$BUCKET_NAME/data
gs://.../data/mnist.pkl
```
Maybe bucket storage is not supported in the trial mode? 
Please help me to fix this error.

**Comment by dneprDroid** [comment]
I'm stupid, forgot about these settings: 
<img width="1001" alt="screen shot 2018-02-16 at 12 04 51 am" src="https://user-images.githubusercontent.com/13742733/36283571-991deaf0-12ad-11e8-997a-153387fce0bf.png">

**Comment by amit0shakya** [comment]
I have already on this option but still getting same error : Bucket is requester pays bucket but no user project provided.


![bucket](https://user-images.githubusercontent.com/4058400/43074729-e5dce872-8e9b-11e8-8e14-0030ac46b9e8.png)

**Comment by mounarajan** [comment]
did u got any solution for this error?

**Comment by LiguoMa274** [comment]
Hi bro
I have that error too
But I set pay to on
What is my issue?

**Comment by amit0shakya** [comment]
Solution is you need add permissions in your IAM user to access S3 bucket objects.

**Comment by LiguoMa274** [comment]
Thanks
I did not set user role for sercive account 😄
Thanks again
________________________________

**Comment by muhammad-al-fahad-21** [comment]
I think you can pay for storage or set billing account
